name: NEXTJS-CI

on:
  push:
    branches: [ "main" ] # Trigger workflow on pushes to the 'main' branch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: BUILD NEXTJS WEB
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          set -e
          
          # Connect to the server
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
            # Load Node.js and npm environment explicitly
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"  # Load nvm if available
            PATH="\$PATH:\$HOME/.nvm/versions/node/v18.17.1/bin" # Adjust for your Node.js version
            
            # Verify Node.js and npm installation
            node -v || { echo "Node.js is not available"; exit 1; }
            npm -v || { echo "npm is not available"; exit 1; }

            cd slot/slot-web

            # Pull the latest code
            git pull
            echo 'Code pulled successfully'

            # Build Next.js app
            npm install --legacy-peer-deps
            npm run build || { echo "Build failed on server, aborting."; exit 1; }
            echo 'Next.js build successful'
          EOF

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Build
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
            cd slot/slot-web

            # Restart the application with PM2
            pm2 restart nextjs || pm2 start npm --name "nextjs" -- run start
            echo 'Next.js Deployment successful to AWS-SERVER'
          EOF
