name: Deploy WEB-CICD

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Pull and Build on Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
          cd slot/slot-web
          git pull origin main # Pull the latest code
          npm install --legacy-peer-deps # Install dependencies
          npm run build || { echo "Build failed, aborting further steps."; exit 1; }
        EOF

  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Restart App
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
          cd slot/slot-web
          pm2 restart 2 || pm2 start 2 # Restart the app if already running, or start it
        EOF
