# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: WEB-CI/CD

on:
  push:
    branches: [ "main" ]
 
permissions:
  contents: read

jobs:
    jobs1:
        runs-on: ubuntu-latest
        steps:
        - name: Creating TRACTOR Build
          uses: actions/setup-node@v3
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_PASSWORD }}

            script: |
              cd slot/slot-web
              git stash
              git pull
              npm run build
              echo 'Build successful '
          
        - name: Deploy TRACTOR Build
          uses: appleboy/ssh-action@v0.1.8
          with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_PASSWORD }}

            script: |
              pm2 restart 4
              echo 'Deployment successful to AWS-SERVER'
