name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build on Server
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          cd slot/slot-web
          git pull origin main
          npm install --legacy-peer-deps
          npm run build || { echo "Build failed, aborting further steps."; exit 1; }
          EOF

  deploy:
    if: success()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restart App on Server
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          cd slot/slot-web
          pm2 start 2
          EOF
