name: Deploy Next.js App

on:
  push:
    branches:
      - main # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.9.0 # Use the appropriate Node.js version

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build Next.js app
      run: npm run build

  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
          cd slot/slot-web
          git pull origin main # Pull the latest code from the repository
          npm install --legacy-peer-deps # Install dependencies
          npm run build || { echo "Build failed on server, aborting deployment."; exit 1; }
          pm2 restart 2 || pm2 start 2 # Restart the app if already running, or start it
        EOF
